### ISSUE TITLE
west skywire format fails on Windows

### ISSUE THREAD

**Issue by kshahar** [NimbeLink/skywire_nano_sdk#1]
Running the following command in the `app` directory fails on Windows:
`west skywire format --input test_sign.pem --type "signkey" --output-file "test.key"`

Output:
```
(venv) C:\dev\SWN\app>west skywire format --input test_sign.pem --type "signkey" --output-file "test.key"
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\User\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\dev\SWN\venv\Scripts\west.exe\__main__.py", line 7, in <module>
    #
  File "c:\dev\swn\venv\lib\site-packages\west\app\main.py", line 779, in main
    app.run(argv or sys.argv[1:])
  File "c:\dev\swn\venv\lib\site-packages\west\app\main.py", line 106, in run
    self.run_command(argv)
  File "c:\dev\swn\venv\lib\site-packages\west\app\main.py", line 338, in run_command
    self.run_extension(args.command, argv)
  File "c:\dev\swn\venv\lib\site-packages\west\app\main.py", line 408, in run_extension
    command.run(args, unknown, self.topdir, manifest=self.manifest)
  File "c:\dev\swn\venv\lib\site-packages\west\commands.py", line 129, in run
    self.do_run(args, unknown)
  File "C:\dev\SWN\skywire_nano_sdk\scripts\dualie.py", line 153, in do_run
    command._runCommand(args = args, unknownArgs = unknownArgs)
  File "C:\dev\SWN\skywire_nano_sdk\scripts\commands\command.py", line 219, in _runCommand
    self.runCommand(args, unknownArgs)
  File "C:\dev\SWN\skywire_nano_sdk\scripts\commands\format.py", line 114, in runCommand
    Dfu.generateBinary(
  File "C:\dev\SWN\skywire_nano_sdk\scripts\tools\dfu.py", line 79, in generateBinary
    with open(file, "rb") as openFile:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\User\\AppData\\Local\\Temp\\tmpbjqcg8z6'
```

I believe the issue is opening the temp file returned by `NamedTemporaryFile` for reading while it is open for writing:

https://github.com/NimbeLink/skywire_nano_sdk/blob/32a96695adafb36b7197eeaf7a5908a9b7f922d3/scripts/commands/format.py#L110-L118
https://github.com/NimbeLink/skywire_nano_sdk/blob/32a96695adafb36b7197eeaf7a5908a9b7f922d3/scripts/tools/dfu.py#L79-L80

Using something like this code seems to work on Windows:
```python
with tempfile.TemporaryDirectory() as tmpdir:
    with open(os.path.join(tmpdir, 'temp.key'), mode = "w+b") as keyFile:
        keyFile.write(bytearray(keyBytes))
        keyFile.flush()

        Dfu.generateBinary(
            file = keyFile.name,
            type = FormatCommand.FriendlyTypes[args.type],
            outputFile = args.outputFile
        )
```
Thanks!

**Comment by erik-johnson-nimbelink** [comment]
Thanks for the suggested code snippet! I've got a slightly different update working here, and I will get it rolled out today for you.

**Comment by erik-johnson-nimbelink** [comment]
Should be fixed for Windows in ae40c61d81127bd7abfba7bf18207527541bd191
